// Jednoduchá vysvětlení pro začátečníky (1–3 věty, plain čeština).
// Klíče odpovídají indexům otázek v TOPICS.

const SIMPLE = {
  t1: [
    'Modelování = vyrobíme si zjednodušený „obraz" reality (rovnice, schéma, fyzický model), abychom ji mohli zkoumat. Místo skutečné továrny napíšeme rovnice popisující výrobu, kapacity a zisk.',
    'Systém je skupina věcí, které spolu nějak souvisí (stroje + lidé + materiál). Než začneme modelovat, musíme vědět, co je uvnitř systému a co je „venku".',
    'Lineární programování (LP) je matematický nástroj, jak najít nejlepší řešení (max zisk / min náklady), když pravidla a omezení jsou lineární. Klasický příklad: kolik čeho vyrábět při omezených zdrojích.',
    'Každý LP model má 4 části: rozhodovací proměnné (o čem rozhoduji), účelovou funkci (co chci max/min), omezení (pravidla, kapacity) a podmínku nezápornosti (x ≥ 0).',
    'Pro úlohu se 2 proměnnými si můžeme přípustnou oblast nakreslit a optimum najít „okem" posunem vrstevnice ÚF. Pro 2 omezení a víc proměnných existuje verze v prostoru požadavků.',
    'Po vyřešení LP musí nastat jeden ze 4 případů: jediné optimum, víc stejně dobrých (alternativní), nekonečné zlepšování (neomezené), nebo žádné přípustné řešení.',
    'Účelová funkce je matematický zápis toho, co optimalizujeme. Příklad: zisk = 30·A + 40·B znamená 30 Kč za kus A a 40 Kč za kus B; chceme to maximalizovat.',
    'Konvexní množina je „rovná" oblast: když si v ní vyznačím 2 body a spojím čárou, čára celá zůstane uvnitř. Přípustná oblast LP je vždy konvexní a optimum leží ve vrcholu.',
    'Obecný zápis modelu pomocí maticí a vektorů: min/max c·x  za podmínek  A·x ≤/=/≥ b,  x ≥ 0. Je to jen úspornější forma toho, co jinak píšeme rovnicemi.',
    'Rozhodovací (strukturní) proměnná je to, o čem rozhoduji – třeba x_1 = počet kusů výrobku A, který chci vyrobit. Její hodnotu určí simplex.',
    'Konkrétní výrobní program: 2 výrobky se zisky 30 a 40 Kč/ks, omezené kapacitou stroje a materiálu. max 30x_1+40x_2 za 2x_1+x_2 ≤ 100, x_1+3x_2 ≤ 90.'
  ],
  t2: [
    'LP má vlastnosti, díky kterým se dá efektivně řešit: vše lineární, věci se sčítají, parametry pevně dané a konečný počet proměnných.',
    'Čtyři pojmy řešení: přípustné = splňuje pravidla, optimální = nejlepší z přípustných, alternativní = víc optim se stejnou hodnotou ÚF, suboptimální = blízko optimu, ale horší.',
    'Bázické řešení je „rohové" – n−m proměnných je nula, zbylých m se dopočítá. V grafu odpovídá vrcholu mnohostěnu. Nebázické není ve vrcholu.',
    'Degenerované řešení je bázické řešení, kde některá z bázických proměnných má hodnotu 0. Vrchol leží na víc omezeních, než by stačilo, a simplex se v něm občas zacyklí.',
    'Tvrdí, že nejlepší řešení vždy najdeme v některém vrcholu mnohostěnu. Proto stačí prohledat konečný počet vrcholů – přesně to dělá simplex.',
    'Stejné 4 případy jako v prostoru řešení, jen viděné z jiné strany: kdy vektor b leží uvnitř jednoho/víc bázových kuželů, mimo ně, nebo „uniká" do nekonečna.',
    'Vektor b musí jít vyjádřit jako nezáporná lineární kombinace sloupců A. Z všech možných „skladů" b vybereme ten s nejlepší hodnotou ÚF.',
    'Vrchol mnohostěnu = roh přípustné oblasti, který nelze vyjádřit jako průměr dvou jiných bodů uvnitř. Kandidáti na optimum LP jsou výhradně vrcholy.',
    'Maximální počet bázických řešení = kolika způsoby lze vybrat m sloupců z n (kombinační číslo). Simplex naštěstí prochází jen malou část z nich.',
    'Konvexní kombinace bodů = vážený průměr s nezápornými váhami součtu 1. Když mám 2 optimální vrcholy, libovolný bod mezi nimi je taky optimum.',
    'Přípustný mnohostěn = množina všech bodů, které splňují všechna omezení modelu. Vznikne průnikem polorovin – tvarem skutečně připomíná mnohostěn.',
    'Klasický příklad: max x_1+x_2 za x_1+x_2 ≤ 10, x ≥ 0. Vrstevnice ÚF je rovnoběžná s omezením, takže celá hrana je optimální (= nekonečně mnoho řešení).'
  ],
  t3: [
    'Aby simplex mohl startovat, úloha musí být v kanonickém tvaru (s jednotkovou bází) a pravé strany ≥ 0. Pak má z čeho začít iterovat.',
    'Doplníme „pomocné" proměnné: u ≤ slack (nevyužitá kapacita), u ≥ surplus + umělou (přebytek), u = jen umělou. Z nerovností se stanou rovnice.',
    'Doplníme proměnné tak, aby v matici vznikla „jednotková" startovací báze. Pro ≤ stačí slack, pro ≥ a = musíme přidat umělé proměnné.',
    'Strukturní (vlastní rozhodnutí), slack (volná kapacita u ≤), surplus (přebytek u ≥), umělé (pomocné jen pro start, v ÚF s velkou penalizací M).',
    'Tři typy: ≤ je strop/kapacita, ≥ je minimum/požadavek (např. dieta), = je přesná rovnost (bilance ve směšovací úloze). Plus podmínka x ≥ 0.',
    'Hlavní pracovní tabulka algoritmu. Obsahuje aktuální bázické řešení, hodnotu ÚF a redukované ceny, ze kterých se pozná, jestli je optimum.',
    'Test, jestli lze řešení ještě zlepšit. Pro max: pokud jsou všechna z_j−c_j ≥ 0, máme optimum. Jinak vstupuje proměnná s nejmenším (nejvíc záporným) z_j−c_j.',
    'Po výběru vstupující proměnné: minimum z poměrů b̄_i/ā_ik (kde ā_ik > 0) určí vystupující bázickou. Tím zaručíme, že nové řešení zůstane nezáporné.',
    'Když chybí přirozená startovací báze: fáze 1 najde jakoukoli přípustnou bázi (minimalizací součtu umělých proměnných), fáze 2 hledá optimum původní ÚF.',
    'Alternativa k dvoufázovému: umělé proměnné dostanou v ÚF obrovský penalizační koeficient ±M. Simplex je sám od sebe vystrká z báze, jinak by porušil ÚF.',
    'Vzácný jev, kdy se simplex „zacyklí" v sérii degenerovaných tabulek. Brání mu Blandovo pravidlo (vybírat proměnnou s nejmenším indexem).',
    'Pivot = klíčové číslo v tabulce na průniku vstupujícího sloupce a vystupujícího řádku. Kolem něj se přepočítá celá tabulka (Gauss-Jordan).',
    'U omezení „2x_1 + x_2 ≤ 100 h" doplníme s_1: 2x_1 + x_2 + s_1 = 100. V optimu s_1 udává, kolik strojohodin zůstalo nevyužitých.'
  ],
  t4: [
    'Bázické proměnné v tabulce poznáš podle sloupce ve tvaru jednotkového vektoru (jedna 1, jinak 0); jejich hodnota = příslušná b̄. Ostatní jsou nebázické s hodnotou 0.',
    'B = aktuální výběr m sloupců matice A. Její inverzi B⁻¹ máme v tabulce „zadarmo" – tam, kde byly původně sloupce výchozí jednotkové báze.',
    'Stínové ceny zdrojů: y_i ukazuje, o kolik se změní ÚF, pokud kapacitu i-tého zdroje zvýším o 1. Najdeš je ve spodním řádku tabulky.',
    'Bázický vektor x_B (rozměr m) obsahuje jen bázické proměnné. Obecný x (rozměr n) obsahuje i nulové nebázické – tedy hodnoty všech proměnných modelu.',
    'Ke každému LP existuje „zrcadlový" duál (max ↔ min, omezení ↔ proměnné). Když má primár hodně proměnných a málo omezení, snazší je řešit duál.',
    'Mechanická pravidla pro převod primáru na duál: prohodit řádky a sloupce, ceny a pravé strany, max ↔ min; ≤ → y ≥ 0; = → y volné.',
    'Pokud má primár optimum, má i duál a hodnoty ÚF se shodují: z*_P = z*_D. Nejdůležitější věta dualitní teorie – kontrolní nástroj pro optimum.',
    'Pokud je v primáru x_j > 0, musí příslušné duální omezení platit v rovnosti (a naopak). Nenulové proměnné = aktivní omezení ve sdružené úloze.',
    'Slabá dualita: pro libovolná přípustná x, y platí c·x ≤ b·y (= jednoduchý odhad). Silná dualita: pokud existují optima, jsou si rovny.',
    'Duální proměnná u zdroje = max cena, kterou se vyplatí za jednotku tohoto zdroje navíc zaplatit. Pokud y_i > nabízená cena externě, vyplatí se zdroj přikoupit.',
    'Konkrétně: u zdroje práce 100 h/týden plně využitého je y = 50 Kč/h. Každá další hodina práce zvýší zisk o 50 Kč. Brigádník za 40 Kč/h se vyplatí.',
    'Z modelu max 5x_1+3x_2, 2x_1+x_2≤10, x_1+x_2≤8 sestrojíme duál: min 10y_1+8y_2, 2y_1+y_2≥5, y_1+y_2≥3, y ≥ 0. (Prohodili jsme čísla a směr nerovností.)'
  ],
  t5: [
    'Když nebázickou proměnnou rozjedeme o θ, bázické hodnoty se podle B⁻¹·a_k zmenšují. Maximální θ = min{b̄_i/ā_ik | ā_ik > 0}, jinak by šly do mínusu.',
    'Spočítáme redukovanou cenu c̄_j = c_j − c_B·B⁻¹·a_j. Pokud zlepšuje, provedeme simplexovou iteraci; pokud ne, ponecháme x_j = 0.',
    'Spočítáme x_B′ = B⁻¹·b′. Pokud zůstane nezáporné, báze platí a ÚF se změní o y_i·Δb_i. Jinak musíme reoptimalizovat (duální simplex).',
    'Říká, do jakého rozsahu mohou pravé strany kolísat, aniž by se změnila optimální báze. Uvnitř ÚF mění lineárně s y_i.',
    'Říká, jak moc se může změnit cena (c_j), aby zůstalo stejné řešení. Pro nebázickou stačí c̄_j ≤ 0; pro bázickou je výpočet složitější.',
    'Výrobní program: max zisk z výroby produktů při kapacitách. Směšovací: min náklady směsi (krmiva, slitiny) splňující kvalitativní požadavky.',
    'Řezné plány: min odpad/počet řezných schémat při splnění poptávky po dílech. Plánování směn: min mzdové náklady při pokrytí poptávky po pracovnících.',
    'Pokud optimum splňuje novou podmínku, řešení zůstává. Jinak ji vložíme do tabulky a duálním simplexem odstraníme nepřípustnost.',
    'Celočíselné programování (IP) = LP s podmínkou „proměnné musí být celé". NP-těžké, řeší se metodou Branch & Bound. Aplikace: výběr projektů, lokace skladů.',
    'Pro nebázickou proměnnou stačí přepočítat redukovanou cenu. Pro bázickou: změna ovlivní inverzní bázi i ostatní sloupce → zpravidla je nutná reoptimalizace.',
    'Interval ⟨b^L; b^U⟩, ve kterém zůstává optimální báze. Uvnitř hodnoty proměnných a ÚF se lineárně mění; mimo musíme reoptimalizovat.',
    'Konkrétně dieta: krmiva A (10 Kč/kg, 5 % bílkovin) a B (8 Kč/kg, 2 %), směs 1 kg s ≥ 4 % bílkovin. min 10x_A+8x_B, 5x_A+2x_B ≥ 4, x_A+x_B = 1.'
  ],
  t8: [
    'Speciální LP: kolik převézt z m dodavatelů k n spotřebitelům, aby celkové dopravní náklady byly minimální. ÚF: min Σc_ij·x_ij.',
    'Vyváženost: Σa_i = Σb_j (nabídka = poptávka). Pokud ne, přidáme fiktivního aktéra s nulovými sazbami.',
    'Nejrychlejší startovní metoda: plníme od levého horního rohu, vždy x_ij = min(a_i, b_j). Hloupá (ignoruje sazby), ale velmi rychlá.',
    'Lepší startovní řešení: vybíráme buňky s nejnižší sazbou. Bere ohledy na c_ij, takže výsledek bývá blíž optimu.',
    'Nejchytřejší startovní metoda: pro každý řádek/sloupec rozdíl 2 nejnižších sazeb (penalta), obsazujeme tam, kde penalta vysoká, v ní nejlevnější buňku.',
    'Když máme méně obsazených polí než m+n−1. Vzniká, pokud se vyčerpá řádek i sloupec naráz. Odstraní se přidáním nulové dodávky (ε ≈ 0).',
    'Vyvážená DÚ má přesně m+n−1 obsazených (bázických) polí. Méně = degenerace, více = není to bázické řešení.',
    'Bilance musí mít rovnicový tvar (Σa = Σb), jinak nelze řešit standardním dopravním algoritmem. Při nerovnováze doplníme fiktivního dodavatele/spotřebitele.',
    'DÚ je speciální LP s 0/1 strukturou matice (totální unimodularita). Při celých vstupech je řešení automaticky celočíselné a stačí použít MODI.',
    'Jednotkový dopravní náklad mezi i a j: Kč/t, Kč/(km·t), h/jednotku atd. Tvoří vstupní data úlohy a c_ij vystupuje jako cenový koeficient v ÚF.',
    'Σa=100, Σb=80 → přebytek 20. Přidáme fiktivního spotřebitele s požadavkem b_{n+1}=20 a sazbami c_{i,n+1}=0. Po dořešení x_{i,n+1} udává nevyužitou kapacitu dodavatelů.'
  ],
  t9: [
    'Test optimality v DÚ: spočítáme u_i, v_j na obsazených polích (u_1=0). Pro neobsazená δ_ij = c_ij − (u_i+v_j). Všechna δ ≥ 0 → optimum.',
    'Uzavřená smyčka v tabulce přes obsazená pole + 1 neobsazené, se střídavými znaménky +/−. Slouží k přepočtu řešení při výměně báze.',
    'Trasa, jejíž zařazení nezhorší ÚF (δ_ij = 0). Značí alternativní optimum – lze ji do plánu zařadit beze ztráty.',
    'Maximální množství, které lze danou trasou převést, aniž bychom porušili kapacity/požadavky. Spočítá se z Danzigova obvodu jako min hodnot v záporných vrcholech.',
    'Všechna δ ≥ 0 znamená, že žádná neobsazená trasa nezlepší ÚF – máme optimum. δ = 0 značí alternativní optimum.',
    'Jiný název pro test optimality přes obvody. Funkčně ekvivalentní MODI – jen pro každou neobsazenou buňku stavíme obvod a počítáme změnu nákladů.',
    '1) Vyvážíme úlohu. 2) Najdeme startovní řešení (SZ roh / index / VAM). 3) Test optimality MODI. 4) Pokud neoptimum: výměna báze přes Danzigův obvod. 5) Opakujeme 3–4.',
    'Pomocné hodnoty = duální proměnné dopravní úlohy. u_i pro dodavatele, v_j pro spotřebitele. Hrají roli stínových cen.',
    'V první iteraci zvolíme u_1 = 0 a postupně z rovnic u_i+v_j=c_ij na obsazených polích dopočítáme všechny zbývající u_i a v_j.'
  ],
  t10: [
    'Speciální DÚ: m=n, kapacity i požadavky = 1, x_ij ∈ {0,1}. Přiřaď každého pracovníka přesně jednomu úkolu, aby celkové ohodnocení bylo min (resp. max).',
    'Rychlý algoritmus pro přiřazovací úlohu. Redukuje řádky a sloupce, hledá nezávislý systém nul, případně dělá další redukce. Složitost O(n³).',
    'Úloha obchodního cestujícího (TSP): navštívit n měst přesně jednou a vrátit se domů co nejkratší cestou. Patří mezi NP-těžké úlohy.',
    'Symetrický × asymetrický (jednosměrky), otevřený × uzavřený (zda se vracet), eukleidovský, mTSP (víc cestujících), VRP (s kapacitami vozidel).',
    'Nejjednodušší heuristika pro TSP: z aktuálního uzlu jdi vždy do nejbližšího nenavštíveného. Rychlé O(n²), ale suboptimální a citlivé na startovní uzel.',
    'VAM upravený pro TSP: penalty na řádcích/sloupcích, blokovaná diagonála (nelze i→i), kontrola podcyklů (předčasné uzavření kratšího cyklu).',
    'TSP heuristika typu „insertion": začneme malou kružnicí ze 3 uzlů a postupně vkládáme nové uzly tam, kde je přírůstek vzdálenosti nejmenší.',
    'Přiřazovací je speciální DÚ s m=n a a=b=1; binární proměnné dávají přiřazení 1:1. Maďarská metoda ji řeší efektivněji než plný dopravní algoritmus.',
    'Exaktní metoda pro NP-těžké úlohy: dělím úlohu na podúlohy (větvení), pro každou počítám dolní mez ÚF, prořezávám větve s horší mezí, než je dosud nejlepší řešení.',
    'Logistika a rozvozové trasy (kurýři, sběr odpadu), servisní výjezdy techniků, vrtání desek plošných spojů, sekvenování DNA.',
    'Konkrétní příklad: 4 pracovníci, 4 úkoly, matice c_ij s dobou zpracování. min Σc_ij·x_ij, Σ_j x_ij=1, Σ_i x_ij=1, x_ij ∈ {0,1}.',
    'V bipartitním grafu G=(U∪V, E): párování, kde každý uzel obou stran má právě 1 partnera. Existuje jen pokud |U|=|V|; modeluje přiřazovací úlohu.'
  ],
  t11: [
    'Graf G=(V,E): V jsou uzly (vrcholy), E hrany. Neorientovaný má hrany bez směru (kamarádství), orientovaný se šipkami (jednosměrky, datový tok).',
    'Hierarchie pojmů: sled (libovolná posloupnost) → tah (bez opakovaných hran) → cesta (bez opakovaných uzlů) → cyklus (uzavřená cesta).',
    'Bez heuristiky – jen procházíme. BFS používá frontu a jde po vrstvách (do šířky); DFS používá zásobník/rekurzi a jde do hloubky.',
    'S heuristikou (odhadem vzdálenosti k cíli). Nejznámější algoritmus je A* s f(n)=g(n)+h(n); při admisibilní h je optimální.',
    'Minimální kostra (MST) = strom spojující všechny uzly s nejmenším součtem vah. Algoritmy: Kruskal (hrany podle vah) a Prim (rozšiřování z uzlu).',
    'Nejkratší cesta z uzlu s do t: Dijkstra (váhy ≥ 0), Bellman-Ford (povolené i záporné, bez záporných cyklů), Floyd-Warshall (pro všechny páry).',
    'Maximální množství, které proteče ze zdroje s do ústí t při daných kapacitách hran. Ford-Fulkerson hledá zlepšující cesty v reziduální síti.',
    'Souvislý neorientovaný graf bez cyklů. Pro n uzlů má přesně n−1 hran. Mezi každými dvěma uzly existuje právě jedna cesta.',
    'Eulerův tah projde každou hranou právě jednou (snadný problém). Hamiltonovský cyklus projde každým uzlem právě jednou (NP-úplný, TSP).',
    'Uzly rozdělíme do 2 disjunktních množin tak, aby hrany vedly jen mezi nimi (ne uvnitř). Modeluje přiřazovací úlohu: pracovníci ↔ úkoly.',
    'Stupeň uzlu = počet hran na něm. Lemma o podání rukou: součet všech stupňů = 2·|E| (každá hrana se počítá v obou koncích).',
    'Maximální podgraf, kde je vše navzájem dosažitelné. Souvislý graf má 1 komponentu; nesouvislý se rozpadá na víc kusů.'
  ],
  t12: [
    'Projekt = dočasné, jedinečné úsilí s definovaným cílem (na rozdíl od rutiny). Klíčová slova: dočasný (začátek/konec), jedinečný, koordinovaný, omezené zdroje.',
    'Činnost = ucelený úkol s dobou trvání (stavba zdi, naprogramování modulu). Zdroj = co k tomu potřebujeme (lidé, materiál, peníze, čas).',
    'Schéma projektu jako orientovaný acyklický graf. AON: uzly jsou činnosti, hrany závislosti. AOA: hrany jsou činnosti, uzly události.',
    'CPM = deterministická síťová analýza s pevnými dobami. Zjistí kritickou cestu, termíny ZM/KM/ZP/KP a rezervy nekritických činností.',
    'Dvě fáze: dopředný chod počítá ZM, KM (nejdříve možné); zpětný chod počítá ZP, KP (nejpozději přípustné) od koncového uzlu.',
    'Nejdelší cesta sítí; činnosti s nulovou celkovou rezervou. Určuje minimální dobu trvání projektu. Zpoždění kritické činnosti zpožďuje celý projekt.',
    'Kolik lze činnost odsunout/prodloužit bez zpoždění projektu. Existuje víc typů: celková (RC), volná (RV), nezávislá (RN), interferenční (RI).',
    'PERT = stochastická verze CPM. Doba činnosti není pevná, ale má 3 odhady: optimistický, nejpravděpodobnější, pesimistický. Umožňuje spočítat pravděpodobnost dokončení.',
    'Očekávaná doba t_e = (a + 4m + b)/6, kde a, m, b jsou optimistický, nejpravděpodobnější a pesimistický odhad. Rozptyl σ² = ((b−a)/6)².',
    'Vizualizace harmonogramu jako sloupcový graf: osa x = čas, osa y = činnosti, délka sloupku = doba trvání. Doplňuje síťový graf o časové rozložení.',
    'Milník = významná událost s nulovou dobou trvání. Příklady: schválení zadání, dokončení návrhu, předání díla, kolaudace. Slouží jako kontrolní bod.',
    'Pro činnost A: ZM=5, KM=10, ZP=8, KP=13. Celková rezerva RC = KP−KM = 3 dny (= ZP−ZM). Lze ji odsunout o 3 dny, aniž by se zpozdil projekt.'
  ]
};
